package com.example.androidclass.repository

import com.example.androidclass.model.City

object CityRepository {
    var cities: List<City> = listOf(
        City(1, "Kazan"),
        City(2, "Moscow"),
        City(3, "Omsk"),
        City(4, "Cullman"),
        City(5, "Clayton"),
        City(6, "Florence"),
        City(7, "Demopolis"),
        City(8, "Eufaula"),
        City(9, "Greenville"),
        City(10, "Riverdale"),
        City(11, "Sweetwater"),
        City(11, "Mobile"),
        City(12, "Orel"),
        City(13, "Ozark"),
        City(14, "Homer"),
        City(15, "Gothem"),
        City(16, "KKazan"),
        City(17, "KMoscow"),
        City(18, "KOmsk"),
        City(19, "KCullman"),
        City(20, "KClayton"),
        City(21, "KFlorence"),
        City(22, "KDemopolis"),
        City(23, "KEufaula"),
        City(24, "KGreenville"),
        City(25, "KRiverdale"),
        City(26, "KSweetwater"),
        City(27, "KMobile"),
        City(28, "KOrel"),
        City(29, "KOzark"),
        City(30, "KHomer"),
        City(31, "KGothem"),
        City(32, "Mazan"),
        City(33, "Moscow"),
        City(34, "Mmsk"),
        City(35, "Mullman"),
        City(36, "Mlayton"),
        City(37, "Mlorence"),
        City(38, "Memopolis"),
        City(39, "Mufaula"),
        City(40, "Mreenville"),
        City(41, "Miverdale"),
        City(43, "Mweetwater"),
        City(44, "Mobile"),
        City(45, "Mrel"),
        )
}
